# Generated by Django 5.2.1 on 2025-05-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avto_mark', models.CharField(choices=[('chevrolet', 'CHEVROLET'), ('lada', 'LADA'), ('porsche', 'PORSCHE'), ('nissan', 'NISSAN'), ('bugatti', 'BUGATTI'), ('lamborgini', 'LAMBORGINI'), ('audi', 'AUDI'), ('mercedes', 'MERCEDES'), ('bmw', 'BMW'), ('toyota', 'TOYOTA')], default='chevrolet', max_length=250, verbose_name='MARC OF THE VEHICLE')),
                ('avto_model', models.CharField(choices=[('sedan', 'SEDAN'), ('suv', 'SUV'), ('hatchback', 'HATCHBACK'), ('pick-up truck', 'PICK-UP TRUCK'), ('crossover', 'CROSSOVER'), ('coupes', 'COUPES'), ('convertible', 'CONVERTIBLE'), ('van', 'VAN'), ('bmw', 'BMW'), ('toyota', 'TOYOTA')], default='sedan', max_length=240, verbose_name='MODEL OF THE VEHICLE')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Cars/')),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('rating', models.PositiveIntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=0)),
            ],
        ),
    ]
